personal_portfolio/blog/urls.py
from django.urls import path
from . import views as blogViews

app_name = 'blog'

urlpatterns = [
    path('', blogViews.all_blogs, name='all'),
    path('<int:blog_id>/', blogViews.detail, name='detail'),
]

personal_portfolio/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

from portfolio import views as portfolioViews

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', portfolioViews.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_portfolio/blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateField(blank=True)
    text = models.TextField(max_length=1000)

    def __str__(self):
        return self.title

personal_portfolio/portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='portfolio/images/', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blog_count = Blog.objects.count
    blogs = Blog.objects.order_by('-date')[:10]
    return render(request, 'blog/all_blogs.html', {'blogs': blogs, 'blog_count': blog_count})


def detail(request, blog_id):
    # pk -> Primary Key
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

personal_portfolio/portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

personal_portfolio/blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html'%} {% block content%} <h1 class="text-center mb-3">Blog</h1>
<h2 class="text-center mb-5">Kostas has written {{ blog_count }} blog{{ blog_count|pluralize }}</h2>
<div class="row mb-5"> {% for blog in blogs %} <div class="col-12 col-sm-6 mb-2">
    <div class="card">
      <div class="card-body">
        <a href="{% url 'blog:detail' blog.id %}">
          <h5 class="card-title">{{blog.title|upper}}</h5>
        </a>
        <h6 class="card-subtitle mb-2 text-muted">{{blog.date|date:'d/m/Y'}}</h6>
        <p class="card-text">{{blog.text|safe|truncatechars:15}}</p>
        <a href="{% url 'blog:detail' blog.id %}" class="btn btn-primary">Read More</a>
      </div>
    </div>
  </div> {% endfor %} </div> {% endblock %}

personal_portfolio/blog/templates/blog/detail.html
{% extends 'portfolio/base.html'%} {% block content%} <h1 class="text-center mb-3">{{ blog.title }}</h1>
<h2 class="text-center mb-3">{{ blog.date|date:'d/m/Y' }}</h2>
<p class="text-justify">{{ blog.text|safe }}</p>
<a href="{% url 'blog:all' %}" class="btn btn-warning mt-3">Return</a> {% endblock %}

personal_portfolio/portfolio/templates/portfolio/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <title>Kostas' Website</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
    <a class="navbar-brand" href="{% url 'home' %}">KG Gkanatsios</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}" target="_blank">Resume</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:all' %}">Blog</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container"> {% block content %} {% endblock %} </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src=" https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
    integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
  </script>
</body>

</html>

personal_portfolio/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html'%} {% block content%} {% load static %} <div class="media mb-5">
  <img src="{% static 'portfolio/my_profile_pic.jpg' %}" class="align-self-center mr-3 rounded img-fluid" width="110"
    alt="Kostas">
  <div class="media-body">
    <h1 class="mt-0">Kostas Gkanatsios</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam perspiciatis repellat expedita reprehenderit
      ratione consequatur, eos deleniti dignissimos id provident obcaecati nostrum cum explicabo earum tenetur
      necessitatibus ipsam beatae excepturi!</p>
  </div>
</div>
<div class="row mb-5"> {% for project in projects %} <div class="col-12 col-sm-6 col-md-4">
    <div class="card">
      <img src="{{project.image.url}}" class="card-img-top" alt="{{project.title}}">
      <div class="card-body">
        <h5 class="card-title">{{project.title}}</h5>
        <p class="card-text">{{project.description}}</p> {% if project.url  %} <a href="{{project.url}}" target="_blank"
          title="{{project.title}}" class="btn btn-primary">Project Link</a> {% endif %}
      </div>
    </div>
  </div> {% endfor %} </div> {% endblock %}